// 初始案件样本数据（覆盖三类复核情形）
import { CaseBatch } from "./types";

export const SEED_BATCHES: CaseBatch[] = [
  {
    id: "CASE-042",
    title: "CASE-042 · 城郊公园草丛案",
    createdAt: "2026-09-10T09:00",
    samples: [
      {
        id: "CASE-042-A",
        caseId: "CASE-042",
        location: "室外草地 · 尸体下方土壤",
        temperature: 26.4,
        exposureStage: "新鲜期",
        species: "丝光绿蝇 Lucilia sericata",
        stage: "卵",
        sampledAt: "2026-09-08T08:30",
        preservation: "75%乙醇保存",
        notes: "卵块集中于自然开孔处",
        pendingRecheck: false,
      },
      {
        id: "CASE-042-B",
        caseId: "CASE-042",
        location: "阴影区域 · 灌丛基部",
        temperature: 28.6,
        exposureStage: "肿胀期",
        species: "丝光绿蝇 Lucilia sericata",
        stage: "幼虫",
        sampledAt: "2026-09-10T07:00",
        preservation: "75%乙醇保存",
        notes: "幼虫三龄，需复核种属",
        pendingRecheck: false,
      },
      {
        id: "CASE-042-C",
        caseId: "CASE-042",
        location: "室外草地 · 距尸体 1.2m",
        temperature: 19.2,
        exposureStage: "腐烂期",
        species: "大隐翅虫 Creophilus maxillosus",
        stage: "成虫",
        sampledAt: "2026-09-12T16:30",
        preservation: "",
        notes: "温度骤降当日采集",
        pendingRecheck: false,
      },
    ],
    reviews: [],
    clears: [],
    adjustments: [],
  },
  {
    id: "CASE-051",
    title: "CASE-051 · 水沟边遗弃案",
    createdAt: "2026-09-11T14:00",
    samples: [
      {
        id: "CASE-051-A",
        caseId: "CASE-051",
        location: "水沟边缘 · 淤泥",
        temperature: 22.0,
        exposureStage: "肿胀期",
        species: "大头金蝇 Chrysomya megacephala",
        stage: "幼虫",
        sampledAt: "2026-09-09T10:00",
        preservation: "75%乙醇保存",
        notes: "二龄幼虫",
        pendingRecheck: false,
      },
      {
        id: "CASE-051-B",
        caseId: "CASE-051",
        location: "水沟边缘 · 石块下",
        temperature: 21.4,
        exposureStage: "腐烂期",
        species: "大头金蝇 Chrysomya megacephala",
        stage: "蛹",
        sampledAt: "2026-09-13T09:20",
        preservation: "干燥针插",
        notes: "蛹壳样本",
        pendingRecheck: false,
      },
    ],
    reviews: [],
    clears: [],
    adjustments: [],
  },
  {
    id: "CASE-063",
    title: "CASE-063 · 废弃仓库案",
    createdAt: "2026-09-15T10:30",
    samples: [
      {
        id: "CASE-063-A",
        caseId: "CASE-063",
        location: "仓库室内 · 水泥地",
        temperature: 18.5,
        exposureStage: "新鲜期",
        species: "厩腐蝇 Muscina stabulans",
        stage: "卵",
        sampledAt: "2026-09-14T11:00",
        preservation: "75%乙醇保存",
        notes: "",
        pendingRecheck: false,
      },
      {
        id: "CASE-063-B",
        caseId: "CASE-063",
        location: "仓库室内 · 货架背阴面",
        temperature: 17.8,
        exposureStage: "肿胀期",
        species: "厩腐蝇 Muscina stabulans",
        stage: "幼虫",
        sampledAt: "2026-09-16T08:40",
        preservation: "75%乙醇保存",
        notes: "一龄",
        pendingRecheck: false,
      },
      {
        id: "CASE-063-C",
        caseId: "CASE-063",
        location: "仓库门口 · 向阳台阶",
        temperature: 30.1,
        exposureStage: "后腐烂期",
        species: "厩腐蝇 Muscina stabulans",
        stage: "成虫",
        sampledAt: "2026-09-17T15:10",
        preservation: "冷藏送检",
        notes: "门口温度探头读数待核",
        pendingRecheck: false,
      },
    ],
    reviews: [],
    clears: [],
    adjustments: [],
  },
  {
    id: "CASE-070",
    title: "CASE-070 · 河道滩涂案",
    createdAt: "2026-09-16T11:00",
    samples: [
      {
        id: "CASE-070-A",
        caseId: "CASE-070",
        location: "河滩芦苇丛",
        temperature: 16.2,
        exposureStage: "腐烂期",
        species: "伏蝇 Phormia regina",
        stage: "蛹",
        sampledAt: "2026-09-15T09:30",
        preservation: "75%乙醇保存",
        notes: "蛹期样本",
        pendingRecheck: false,
      },
      {
        id: "CASE-070-B",
        caseId: "CASE-070",
        location: "河滩芦苇丛 · 上游 5m",
        temperature: 15.8,
        exposureStage: "肿胀期",
        species: "伏蝇 Phormia regina",
        stage: "幼虫",
        sampledAt: "2026-09-16T10:00",
        preservation: "75%乙醇保存",
        notes: "采样记录与发育顺序矛盾，待核实",
        pendingRecheck: false,
      },
    ],
    reviews: [],
    clears: [],
    adjustments: [],
  },
];
